### ISSUE TITLE
Questions about the performance reading the model and the configuration

### ISSUE THREAD

**Issue by cortze** [sigp/blockprint#25]
## Description
I just downloaded the "raw" block rewards for ~`6M` main net slots (~1TB of data), which after the classification, stays in ~130GB of "model" (see table below).
```
The model (size):
2.5G    ./model/Prysm
4.3G    ./model/Nimbus
31G     ./model/Teku
1.2G    ./model/Lodestar
92G     ./model/Lighthouse
130G    ./model
```
There are a few questions I would like to open here:
1. Is this an overkilling number of block rewards to train the model?
I'd like to have an accurate enough model, but this seems a bit overkill to me. I'm unsure if you could guide me here based on your experience. 

2. Loading the model currently takes around 50mins, is this an expected duration for the range of time I'm managing?
I checked if there is any concurrency parameter that I could be missing when loading the model (meaning creating an object [`Classifier`](https://github.com/sigp/blockprint/blob/02c9f80dbaa0bcd6756a209de20fca9f30a5b3e3/knn_classifier.py#L63) from the given model/folder), but it seems to be sequential by itself. 

3. I also have some doubts about the possible features of the `Classifier`. I'm currently using the [default ones](https://github.com/sigp/blockprint/blob/02c9f80dbaa0bcd6756a209de20fca9f30a5b3e3/knn_classifier.py#L23), and I'll like to know if you guys have better performance using a different combination of features.

Many thanks in advance, and great work with this repo!

**Comment by michaelsproul** [comment]
> 1. Is this an overkilling number of block rewards to train the model?

Yes, I think so! For the prod instance I'm still using a very old snapshot of blocks between slots 3760129 and 3981312. It's performing OK for now (see https://api.blockprint.sigp.io/confusion), but is in need of an upgrade.

> 2. Loading the model currently takes around 50mins, is this an expected duration for the range of time I'm managing?

Yeah, which is why I'd recommend using a smaller model. As far as my testing shows, larger models don't provide significantly better results. Alternatively you can pickle the model rather than rebuilding it fully. Aris added some tools for doing this, although I personally don't use them.

> I also have some doubts about the possible features of the Classifier. I'm currently using the [default ones](https://github.com/sigp/blockprint/blob/02c9f80dbaa0bcd6756a209de20fca9f30a5b3e3/knn_classifier.py#L23), and I'll like to know if you guys have better performance using a different combination of features.

At the moment the default features are the best as far as I'm aware. But as I said, the training data is probably in need of a refresh and re-evaluation.

My TODO list for blockprint is something like:

- Add Grandine support to the DB
- Collect a bunch of blocks for minority clients like Lodestar/Grandine/Nimbus/Teku using [blockdreamer](https://github.com/michaelsproul/blockdreamer/).
- Train a new model with a balanced number of blocks per client (e.g. 10K). Use the "synthetic" blocks from blockdreamer to supplement the canonical ones. See the `balance.py` script.
- Re-run cross validation with different feature sets on this new model.
- Deploy the new model and continue measuring its accuracy with blockdreamer+blockgauge (the backed for https://api.blockprint.sigp.io/confusion).

If you have any bandwidth to help with this, I could do with a hand! I'm basically drowning in work of all sorts and don't have much time for blockprint at the moment

**Comment by cortze** [comment]
Hey @michaelsproul , many thanks for the quick response! 

> Yes, I think so! For the prod instance I'm still using a very old snapshot of blocks between slots 3760129 and 3981312. It's performing OK for now (see https://api.blockprint.sigp.io/confusion), but is in need of an upgrade.

> Yeah, which is why I'd recommend using a smaller model. As far as my testing shows, larger models don't provide significantly better results. Alternatively you can pickle the model rather than rebuilding it fully. Aris added some tools for doing this, although I personally don't use them.

I'll work on reducing the number of samples we keep for `Teku` and `Lighthouse`, trying to keep a constant number of samples for each client. I'm not sure if "pickling" the model is necessary in our case, as we (@migalabs) just use it for internal purposes, and reducing the overall size of the model will definitely help us 🤣 

The roadmap you just introduced is pretty exciting, I'll try to see if anyone from the team can allocate some time to give you a hand 😄 

Congrats on this amazing work! 🚀
